### ISSUE TITLE
HiDPI support for ProMesh on Mac OS

### ISSUE THREAD

**Issue by miho** [sreiter/ProMesh#1]
HiDPI mode on Mac OS would be a very nice feature for ProMesh. To enable HiDPI mode on Mac OS X it is necessary to add the following entry to the plist-File of the application bundle:

```
    <key>NSHighResolutionCapable</key>
    <string>false</string>
```

The implementation of the the mouse event handling in the 3D view needs to take the ratio between real and virtual pixel density into account. All the Qt related event handling (buttons&menus) should work without any changes.

**Comment by stephanmg** [comment]
I agree, this would be a nice enhancement.

**Comment by sreiter** [comment]
Thanks for your input! I'll have a look at it.

**Comment by miho** [comment]
The QScreen class might help here: http://doc.qt.io/qt-5/qscreen.html#physicalDotsPerInch-prop and http://doc.qt.io/qt-5/qscreen.html#logicalDotsPerInch-prop

**Comment by sreiter** [comment]
This issue should be resovled by now (thanks @mastep84 ). If you still experience problems, feel free to reopen.
Kind regards,
Sebastian
