### ISSUE TITLE
Proper way to cite ProMesh

### ISSUE THREAD

**Issue by stephanmg** [sreiter/ProMesh#11]
Dear Sebastian,

I would like to incorporate a citation for ProMesh for one of my papers I am currently preparing. 

Is this the correct Bibtex entry? Or should I use a different one?

```
@article{Reiter2012,
  author = {Reiter, S.},
  title = {ProMesh -- a flexible interactive meshing software for unstructured hybrid grids in 1, 2, and 3 dimensions},
  journal = {Comp Vis Sci. (in preparation)},
  year = {2012}
}
```

Thank you so much!

**Comment by sreiter** [comment]
I would just cite the homepage www.promesh3d.com
Thanks!
