### ISSUE TITLE
Assignment of subset colors or change of subset names removes custom attachments from .ugx after saving

### ISSUE THREAD

**Issue by stephanmg** [sreiter/ProMesh#12]
I realized that either  of the following actions in ProMesh (4.3.17 on OSX / 4.3.18 on Linux) will remove my custom attachments after I save it to `.ugx`:

- Assign Subset Colors
- Rename Subset

Is this intended? I was under the impression that renaming the subset and change of colors should not interfere with the attachments per se.

**Comment by sreiter** [comment]
This is not intendet. Custom attachments are probably not the most widely used feature and thus their support may not be optimal in all places.
If you intend to supply a patch I'd be more than happy to look at it!

**Comment by stephanmg** [comment]
Okay, could you give maybe any hints at which level of abstraction I should be trying to write a fix?

**Comment by sreiter** [comment]
Hi Stephan,
Could you please provide a sample data set with custom attachments and a step-by-step guide describing the actions you are performing? I will have a look at it.
Thanks! Kind regards,
Sebastian

**Comment by stephanmg** [comment]
Here it is.
I'd/we like to reassign geometric elements to subsets, change subset names and colors of subsets if possible.

[example_for_sebastian.zip](https://github.com/sreiter/ProMesh/files/6181377/example_for_sebastian.zip)

**Comment by sreiter** [comment]
Hi Stephan,
it seems custom attachments are not preserved on save. Never. This is not related to any operation you're performing. Simply open the geometry and save it again - and the custom attachments are gone.
This seems to be unsupported, currently.
If you're only assigning subset colors and not performing any vertex operations, you may use the following workaround:
- open the geometry in promesh
- perform subset operations
- save the geometry under a different name
- manually copy the two lines which contain the custom vertex attachments to the new file.
Sorry - that's a bit late and just a very rough workaround.

As I said, custom attachments are not a widely used feature in ProMesh, as far as I know. If you or somebody else who uses custom attachments would like to try to fix this, I'd happily offer feedback on a branch or a merge request.

**Comment by stephanmg** [comment]
Hi @sreiter,

yeah that's what we did in the past.
I understand that it is not supported yet, however it would be a welcome addition. Since I've also no time right now to implement this feature, I would just kindly ask to consider it for the future. The issue can be closed, maybe it can be a added to the ProMesh roadmap or so, I do not know.

Cheers!
