### ISSUE TITLE
Warning: iCCP incorrect sRGB profile

### ISSUE THREAD

**Issue by stephanmg** [sreiter/ProMesh#14]
FWIW I think this can be ignored (Looks like libpng has more strict profile checking, see 
https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile)

Just to let you know, this is output to my terminal in Ubuntu 20.04 when invoking ProMesh. The program functions totally fine as expected.

```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

Stephan

**Comment by sreiter** [comment]
Interesting, thanks! However, since this does not hamper the usability I will close the issue for now. If there was a merge request which fixes the issue, I would of course be happy to merge it to master 😅

**Comment by stephanmg** [comment]
Well, yeah, I think one can't do too much unless one wants to tinker with the (external to ProMesh) library libpng.
