### ISSUE TITLE
Erase dialog does not disappear

### ISSUE THREAD

**Issue by chriamue** [sreiter/ProMesh#2]
When selecting a vertex and press delete button a dialog appears, but after applying the dialog still exists.
And there are no cancel buttons.

My system: Ubuntu 16.10, cinnamon desktop environment.
![erase_dialog](https://cloud.githubusercontent.com/assets/7541795/21155203/78453ae2-c171-11e6-8095-456dd00d6fc6.png)

**Comment by sreiter** [comment]
Thanks for your message. Actually, there should be a close button in the window header. However, I didn't test it with cinnamon desktop yet.
Did you test the precompiled ProMesh 4.3.2 version from www.promesh3d.com? Or did you compile yourself and had those issues?

Thanks again and kind regards,
Sebastian

**Comment by parnet** [comment]
Same problem on Ubuntu 19.04 with ProMesh 4.3.17.
In the Scene Inspector when pressing "Del" on the keyboard.

A close button exists but clicking on apply does nothing.

**Comment by sreiter** [comment]
Thank's for your comment. Which desktop do you use? Also cinnamon?
Kind regards,
Sebastian

**Comment by parnet** [comment]
No I am Using Gnome (GNOME Shell 3.32.0) 

Best regards
parnet

**Comment by sreiter** [comment]
Maybe I misunderstood. The apply button is not intended to close the dialog. Maybe this is a bit misleading. The idea is that you can delete several different selections without opening the dialog again.
Just to clarify:
1. The close button closes the dialog?
2. Apply deletes the selected geometry but does not close the dialog?

If this is the case, the behavior would be as intended.

Thanks and kind regards,
Sebastian
