### ISSUE TITLE
ProMesh silently ignores faces with more than four vertices when loading .obj files

### ISSUE THREAD

**Issue by miho** [sreiter/ProMesh#3]
Hi Sebastian,

it would be cool if you could add a warning to the log which indicates which faces cannot be rendered and/or processed with ProMesh.

Thanks,
Michael

**Comment by sreiter** [comment]
Hi Michael,

thanks for your comment. I added a check to the loader in ug4/ugcore. The next ProMesh version (4.3.5) will contain it.

Regards,
Sebastian
