### ISSUE TITLE
ProMesh live script editor

### ISSUE THREAD

**Issue by stephanmg** [sreiter/ProMesh#8]
Hello,

(This is more a question than a real issue)

I would like to know how the Lua code one inputs in the live script editor in ProMesh is executed.

I would need to set an environment variable in the live script editor. While I know there are 'luaposix' and 'winapi' modules one could use to set environment variables (setenv), it would be interesting if it can be done somehow differently with only the live script editor. I assume after click on the `Apply` button a Lua shell is executed in a separate process and the script is executed? 

Could you give some explanations possibly on how the code is run I input in the live script editor?

Kind regards,
Stephan

**Comment by sreiter** [comment]
Hi,
the Lua interpreter is actually compiled into ProMesh. No separate process or shell ist started for it. If you want to use environment variables, you would probably have to set them in the shell in which ProMesh is launched.
The Live-Script editor is mainly meant to help developing scripts. To run scripts, it is still recommended to store a script with parameters in your .promesh/scripts folder. It will then be available as a tool in ProMesh's Tools/Scripts panel.
Hope this helps a bit.
Kind regards,
Sebastian

**Comment by stephanmg** [comment]
This helps indeed. Parameters are too variable, so I think it would not be too useful for us. Is there a possibility to include the script in the tools dialog in ProMesh with input fields without modifying ProMesh directly? (I would think no)

The shell information is very helpful! Thank you.

**Comment by stephanmg** [comment]
Any progress here? Or do I need to provide more information?

**Comment by sreiter** [comment]
_"Is there a possibility to include the script in the tools dialog in ProMesh with input fields without modifying ProMesh directly?"_

Yes. This is how ProMesh scripts work. You declare variables through comments in your script and those will be displayed as input fields in the tool dialog.

Just create a new script through ProMeshs `Scripts-NewScript` menu entry and pick a filename. Your new script has a comment explaining how it works and some sample variables.

After saving the script make sure to hit `Scripts-RefreshToolDialogs` so that the scripts tool dialog appears and is updated. Do so after each change (save beforehand).

Here's the content of the `Scripts-NewScript` script file:
```
--------------------------------------------------------------------------------
-- Lua-Script for ProMesh4
-- The variable 'mesh' contains the mesh object on which the script shall operate
-- The pm-declare- comments define the resutling tool's name ('pm-declare-name')
-- and the script's input parameters ('pm-declare-input'). Sample names and
-- parameters are provided. They can be erased or changed as required.
--
-- 'pm-declare-input' has the following sections, each separated by '|':
--		1: the name under which the input-parameter is accessible in the script
--		2: the name of the input-parameter as it appears in promesh
--		3: the type of the input-value (double, integer, boolean, string)
--		4: default-, minimal- and maximal-values, number of digits (only double)
--		   and the step-size, which defines how much a value is increased or
--		   decreased when the up/down arrows are pressed. The different values
--		   can be set through 'val', 'min', 'max', 'digits', and 'step'. If more
--		   than one value is specified, they have to be separated by ';'.
--
-- If you're editing a script while ProMesh is running, press
-- Scripts-RefreshToolDialogs to update the associated tools content.
--------------------------------------------------------------------------------

-- pm-declare-name: New Script
-- pm-declare-input: doubleValue | double value | double | val = 0; min = 0; max = 360; digits = 2; step = 0.1
-- pm-declare-input: integerValue | integer value | integer | val = 0
-- pm-declare-input: boolValue | boolean value | boolean | val = false
-- pm-declare-input: stringValue | string value | string | val = some string
```

**Comment by stephanmg** [comment]
> After saving the script make sure to hit `Scripts-RefreshToolDialogs` so that the scripts tool dialog appears and is updated. Do so after each change (save beforehand).

I missed this. Now it is working. Thank you!
