### ISSUE TITLE
Failed to read attachment entry

### ISSUE THREAD

**Issue by stephanmg** [sreiter/ProMesh#9]
One of my colleagues is facing this potential problem in ProMesh 4.3.17 (OSX: Catalina):

```
loading
/Users/jamesrosado/Desktop/vr-grids/Code/JamesTest/Foobar/0-2a_original/0-2a_original_segLength=3_3d_x1.ugx
...

ERROR: Failed to read attachment entry.
```

The geometry will not be loaded if, e.g. a custom attachment is stored in the `.ugx` file. 
For me it works (Not Catalina), i.e. read and display the geometry and if I remember correctly on Ubuntu 16.04 as well.

Should it always fail to read and display `.ugx` files in ProMesh with custom attachments and I am only lucky that it works?

Best wishes,
Stephan

**Comment by sreiter** [comment]
Hi,
could you please provide a small sample .ugx file which doesn't work on your colleagues Mac? This would make it easier to identify the issue.
Thanks and kind regards,
Sebastian

**Comment by sreiter** [comment]
Oh - and what computer/OS are you using precisely? Also a Mac?

**Comment by stephanmg** [comment]
> Hi,
> could you please provide a small sample .ugx file which doesn't work on your colleagues Mac? This would make it easier to identify the issue.
> Thanks and kind regards,
> Sebastian

So sorry, I forgot to attach the file.

**Comment by stephanmg** [comment]
Example file below:
[10-dkvm2_x2.ugx.zip](https://github.com/sreiter/ProMesh/files/5015166/10-dkvm2_x2.ugx.zip)

I am using Mac OSX El Capitan on a Macbook Pro. Ubuntu 16.04 on a regular Desktop PC.
My colleague and PI both use Desktop Mac with OSX Catalina.

ProMesh version 4.3.17 for all of us.

**Comment by stephanmg** [comment]
Any progress on this? Or do you need more information?

**Comment by sreiter** [comment]
Normally, custom attachments should be ignored. However, the attachments here belong to the NeuriteProjector, which is actually part of ProMesh, as far as I can tell. Never used it though.

Could you compile ProMesh from source on the computers having issues and look into it? You should be able to tell why reading the attachment fails by stepping into it with the debugger.

We can discuss any findings, of course.

**Comment by stephanmg** [comment]
Okay, I will compile from source and step through with the debugger. Once done I will report back here.

Update: This does not happen for me for the compiled from source version - only in the precompiled binary I can reproduce this on my computer.

**Comment by sreiter** [comment]
I'm just now preparing a new build and checked your comments again. The NeuriteProjector was primarily an addition to UG4 and was thus not officially documented in the ProMesh recent changes document. Version 4.3.17 was released in April 2018 whereas the NeuriteProjector was introduced in October 2018 and first contained in ProMesh version 4.3.18. However, unfortunately there was no 4.3.18 release for OSX.
I'm now preparing a 4.3.19 release and will close this issue once the OSX build is live.

**Comment by stephanmg** [comment]
@sreiter well appreciated!

Please note: Actually on Windows 10 I could read the `.ugx` files even in the presence of the NeuriteProjector attachment handler.

**Comment by sreiter** [comment]
@stephanmg
> Please note: Actually on Windows 10 I could read the .ugx files even in the presence of the NeuriteProjector attachment handler.

I guess you were using ProMesh4.3.18 there? Then this would be expected.

**Comment by stephanmg** [comment]
I do not recall because I don't have Windows system setup any more, but I downloaded this a month ago from your website.

**Comment by sreiter** [comment]
@stephanmg: I updated the OSX installer on the homepage (www.promesh3d.com) to 4.3.19. Would be cool if you could check if it works for you now, and eventually close this ticket.
Thanks!

**Comment by stephanmg** [comment]
Hi I can check it out tomorrow. Thank you! (With Ubuntu there should be no problem anyway, right?)

**Comment by sreiter** [comment]
I also updated the linux and windows installers to 4.3.19. But they didn't have this issue.

**Comment by stephanmg** [comment]
Okay, for me this works now. Thus I think this issue can be closed.
